### ISSUE TITLE
UserData script is broken

### ISSUE THREAD

**Issue by tsamaya** [jicowan/hello-world#1]
Hi
trying to follow this tutorial, the jenkins server is not setup on my side:
https://github.com/jicowan/hello-world/blob/5843594d725ac1398abf8865c12171495429623d/ecs-jenkins-demo.template#L433
I manually did the command on the ec2 instance to get to the next step of the tutorial (https://github.com/awslabs/aws-cicd-docker-containers)

**Comment by jicowan** [comment]
@tsamaya What is the issue?  Are you using the getting started guide, https://docs.aws.amazon.com/AWSGettingStartedContinuousDeliveryPipeline/latest/GettingStarted/CICD_Jenkins_Pipeline.html.

**Comment by tsamaya** [comment]
yes I am following this tutorial, actually the version directly from github.

the JenkinsStack creates and has a CREATE_COMPLETE status but Jenkins is not installed.

Someone encountered the same issue few weeks ago: https://github.com/awslabs/aws-cicd-docker-containers/issues/4

As I must admit to be a perfect beginner with CloudFormation, I did manually the steps in the UserData to be able to do the next steps

by the way: your tutorial is awesome and meets exactly my need.

**Comment by jicowan** [comment]
I had to update the AMI mappings in the template.  It should work now.

**Comment by tsamaya** [comment]
Thank you for the update, I will try it as soon as possible. have a great week end
